server:
  port: 8001


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudplanner?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root



mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yangyang.cloud.entities
  configuration:
    map-underscore-to-camel-case: true



