server:
  port: 80


spring:
  cloud:
    consul:
      host: 192.168.10.105
      port: 8500
      discovery:
        service-name: ${spring.application.name}

        heartbeat:
          enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudplanner?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  application:
    name: task-submission-service